### ISSUE TITLE
Incorrect Time difference

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/async-comm#2]
I am getting the following log:
_level=info msg="Time App-A-producerX-05:09:14:13:26.809 remained in the Queuing System: **19800008ms**"_

Time difference computation is definitely not correct. Please fix it.

**Comment by parvez0** [comment]
This is resolve with the latest commit, it was happening because of the time zone difference, right now I have setup the timezone to IST

**Comment by kiran-anand14** [comment]
Resolved.
