### ISSUE TITLE
Code is crashing on providing output_file_path

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/async-comm#3]
On setting output_file_path in config file, code is crashing.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b8960]

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Logger).level(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:352
github.com/sirupsen/logrus.(*Logger).IsLevelEnabled(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:374
github.com/sirupsen/logrus.(*Logger).Logf(0x0, 0x0, 0x40ee1d, 0x27, 0x40002dfdb8, 0x2, 0x2)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:149 +0x20
github.com/sirupsen/logrus.(*Logger).Panicf(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:192
main.InitializeLogger(0x4000240240, 0x673cd8, 0x673cd8)
        /app/internal/app/asynccommtest/logger.go:56 +0x300
main.init.0()
        /app/internal/app/asynccommtest/main.go:18 +0x44
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b8960]

**Comment by parvez0** [comment]
Logrus is crashing if the path of the file doesn't exist, the error log is not clear I have implemented the changes I will create a pull request after some more tests.

**Comment by kiran-anand14** [comment]
Let me know once you fix it.

**Comment by parvez0** [comment]
this was also fixed with the latest changes can you test it out

**Comment by kiran-anand14** [comment]
Ok, I will test it.
