### ISSUE TITLE
Message pull time is not proper

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/async-comm#5]
Have a look at the following logs. Pull time is not making any sense to me. Producer pushed message at 05:12:**14:10:26.311** and following trace is showing it was pulled at 05:12:**08:40:36.251**. How can it be so? Please fix it, all these message are showing wrong time.

"Pulled App-A-producerX-05:12:14:10:26.311 at 05:12:08:40:36.251 by consumerZ"

Moreover, based on the above log, you are printing following log:
"Time App-A-producerX-05:12:14:10:26.311 remained in the Queuing System: 9940ms"

I don't how this calculation is happening? Basically, fix the pull related log and fix this calculation.

Just to mention, following time print and calculcations are correct:
"Processing over for App-A-producerX-05:12:14:10:26.311 at 05:12:14:10:38.252"
"Total Time taken for processing App-A-producerX-05:12:14:10:26.311: 11941ms"

**Comment by parvez0** [comment]
How are you running this application can you tell me

**Comment by kiran-anand14** [comment]
Here is the tc-1-config-app-1.yaml that I am using:

# redis connection information
redis:
  host: localhost
  port: 6379
  username: ""
  password: ""

# act_app_logger configuration
app_logger:
  level: info
  full_timestamp: true
  output_file_path: ""

# ac library logger configuration
ac_logger:
  level: info
  output_file_path: ""

# application information
application:
  app: App-A
  routines:
    - role: producer
      q: req-a-q #group req-q-consumer-group
      name: producerX
      message:
        format: "{{.App}}-{{.Producer}}-{{.Time}}"
        freq: 500
    - role: consumer
      q: req-a-q
      name: consumerX
      processing_time: 1000
      refresh_time: 5000
      claim_time: 5000
      msg_idle_time: 5000
      block_time: 200
    - role: consumer
      q: req-a-q
      name: consumerY
      processing_time: 1000
      refresh_time: 5000
      claim_time: 5000
      msg_idle_time: 5000
      block_time: 200

Here is the docker compose file:

version: '3.7'

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  redis:
    image: redis:6.2.2
    ports:
      - "6389:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "info"]
      interval: 30s
      timeout: 20s
      retries: 3

  app:
    image: asynctest:0.1
    hostname: app
    restart: on-failure
    links:
      - redis
    environment:
      REDIS.HOST: redis
      REDIS.PORT: 6379
    volumes:
      - ./tc-1-config-app-1.yaml:/etc/async-comm/config.yaml

**Comment by kiran-anand14** [comment]
Here is the tc-1-config-app-1.yaml:

`# redis connection information
redis:
  host: localhost
  port: 6379
  username: ""
  password: ""

# act_app_logger configuration
app_logger:
  level: info
  full_timestamp: true
  output_file_path: ""

# ac library logger configuration
ac_logger:
  level: info
  output_file_path: ""

# application information
application:
  app: App-A
  routines:
    - role: producer
      q: req-a-q #group req-q-consumer-group
      name: producerX
      message:
        format: "{{.App}}-{{.Producer}}-{{.Time}}"
        freq: 500
    - role: consumer
      q: req-a-q
      name: consumerX
      processing_time: 1000
      refresh_time: 5000
      claim_time: 5000
      msg_idle_time: 5000
      block_time: 200
    - role: consumer
      q: req-a-q
      name: consumerY
      processing_time: 1000
      refresh_time: 5000
      claim_time: 5000
      msg_idle_time: 5000
      block_time: 200
`

Here is the docker-compose file:
`# redis connection information
redis:
  host: localhost
  port: 6379
  username: ""
  password: ""

# act_app_logger configuration
app_logger:
  level: info
  full_timestamp: true
  output_file_path: ""

# ac library logger configuration
ac_logger:
  level: info
  output_file_path: ""

# application information
application:
  app: App-A
  routines:
    - role: producer
      q: req-a-q #group req-q-consumer-group
      name: producerX
      message:
        format: "{{.App}}-{{.Producer}}-{{.Time}}"
        freq: 500
    - role: consumer
      q: req-a-q
      name: consumerX
      processing_time: 1000
      refresh_time: 5000
      claim_time: 5000
      msg_idle_time: 5000
      block_time: 200
    - role: consumer
      q: req-a-q
      name: consumerY
      processing_time: 1000
      refresh_time: 5000
      claim_time: 5000
      msg_idle_time: 5000
      block_time: 200
`

**Comment by kiran-anand14** [comment]
Attaching configuration files:

[config-files.tar.gz](https://github.com/kiran-anand14/async-comm/files/6467016/config-files.tar.gz)

**Comment by kiran-anand14** [comment]
Seems resolved, more testing will be needed at higher workloads.
