### ISSUE TITLE
Pending message claim is running continuously

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/async-comm#8]
Check below logs, code is trying to claim messages on every Pull() whereas it should try to pull a message only if claimTime duration has elapsed since last Pull. In my config file, claimTime is set to 5000 ms.

app_1    | [DEBUG]: 2021-05-14 **09:32:34** -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1    | [DEBUG]: 2021-05-14 **09:32:34** -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'

Please test the code thoroughly from the perspective of all configurable timers - claimTime, refreshTime, blockTime, claimTime etc.

**Comment by parvez0** [comment]
for me it is working fine 

Starting asynccommtest_app_1           ... done
Creating asynccommtest_app-altername_1 ... done
app_1            | [DEBUG]: 2021-05-17 10:03:51 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:03:53 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:03:55 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:03:57 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:03:59 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:04:01 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:04:03 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:04:05 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:04:07 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:04:09 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:04:11 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:04:13 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:04:15 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:04:17 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:04:19 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:04:21 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'
app_1            | [DEBUG]: 2021-05-17 10:04:23 -- [ AsyncComm ] -- - pending message claim request initiated by consumer 'consumerX'

this is my configuration 
    - role: consumer
      q: req-f-q
      name: consumerX
      processing_time: 2000
      refresh_time: 2000
      msg_idle_time: 100

Please note that the claim works on refresh_time so if it's < processing_time it will run on every pull

**Comment by kiran-anand14** [comment]
"Please note that the claim works on refresh_time" - This understanding is wrong. refresh_time is the time after which consumer indicates its liveness. How is it related to claim time? Moreover, what is the use of claim_time then if refresh_time is guiding time to claim a message?

Test your code with:
      processing_time: 500
      refresh_time: 5000
      claim_time: 5000
      msg_idle_time: 5000
      block_time: 200

And please read the Appendix A thoroughly and if you have any doubt in understanding the process to claim a message, then again discuss it with me.

**Comment by parvez0** [comment]
Hey Kiran sorry I meant Claim Time any way there was a bug and this is fixed now

**Comment by kiran-anand14** [comment]
Ok

**Comment by kiran-anand14** [comment]
It is working now.
