### ISSUE TITLE
docker images keep growing

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/async-comm#9]
On checking with "docker images" command after making building an image, intermediary images are not getting cleared.

**Comment by parvez0** [comment]
are you talking about the docker image size?

**Comment by kiran-anand14** [comment]
No, I am talking about the **number** of docker images.

**Comment by parvez0** [comment]
Yes that's how Docker builds the layer you have to delete it manually that cannot be managed from the docker image, you can delete the unused images by running this command docker system prune --volumes

**Comment by kiran-anand14** [comment]
Ok, thanks.

For myself, this also works: docker rmi $(docker images --filter 'dangling=true' -q --no-trunc)
